#指定运行环境
#language: node_js
#指定nodejs版本，可以指定多个
#node_js:
#  - 0.12.5

#运行的脚本命令
#script:
#  - npm run ci

#指定分支，只有指定的分支提交时才会运行脚本
#branches:
#  only:
#    - master

#language: node_js
#node_js:
#    - "6"
#git:
#  submodules: false
#install:
#    - npm install
#test:
#    - npm run test

language: android

jdk: oraclejdk8

android:
  components:
    - tools
    - android-24
    - build-tools-24.0.2
    - platform-tools

script: ./gradlew build

after_success:
  - for name in $(find $TRAVIS_BUILD_DIR -name '*.apk'); do ls -hl $name;  done
  - date

after_failure:
  for name in $(find $TRAVIS_BUILD_DIR -name lint-results*.xml); do echo $name; cat -n $name; done

# vim: set shiftwidth=2 tabstop=2 softtabstop=-1 expandtab:
